#!/bin/bash

HAS_NODE=`which node 2> /dev/null || which nodejs 2> /dev/null || which iojs 2> /dev/null`

# TAKEN FROM pre-commit node module
# There are some issues with Source Tree because paths are not set correctly for
# the given environment. Sourcing the bash_profile seems to resolve this for bash users,
# sourcing the zshrc for zshell users.
#
# https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly
#
function source_home_file {
  file="$HOME/$1"
  [[ -f "${file}" ]] && source "${file}"
}

if [[ -z "$HAS_NODE" ]]; then
  source_home_file ".bash_profile" || source_home_file ".zshrc" || source_home_file ".bashrc" || true
fi



git stash -q --keep-index

NODE=`which node 2> /dev/null`
NODEJS=`which nodejs 2> /dev/null`
IOJS=`which iojs 2> /dev/null`
LOCAL="/usr/local/bin/node"

if [[ -n $NODE ]]; then
  "$NODE" $("$NODE" -e "console.log(require.resolve('pre-push'))")
elif [[ -n $NODEJS ]]; then
  "$NODEJS" $("$NODEJS" -e "console.log(require.resolve('pre-push'))")
elif [[ -n $IOJS ]]; then
  "$IOJS" $("$IOJS" -e "console.log(require.resolve('pre-push'))")
elif [[ -x $LOCAL ]]; then
  "$LOCAL" $("$LOCAL" -e "console.log(require.resolve('pre-push'))")
fi
RESULT=$?

git stash pop -q
[ $RESULT -ne 0 ] && exit 1
exit 0

