#!/bin/bash

git stash -q --keep-index

NODE=`which node 2> /dev/null`
NODEJS=`which nodejs 2> /dev/null`
IOJS=`which iojs 2> /dev/null`
LOCAL="/usr/local/bin/node"

if [[ -n $NODE ]]; then
  "$NODE" $("$NODE" -e "console.log(require.resolve('pre-push'))")
elif [[ -n $NODEJS ]]; then
  "$NODEJS" $("$NODEJS" -e "console.log(require.resolve('pre-push'))")
elif [[ -n $IOJS ]]; then
  "$IOJS" $("$IOJS" -e "console.log(require.resolve('pre-push'))")
elif [[ -x $LOCAL ]]; then
  "$LOCAL" $("$LOCAL" -e "console.log(require.resolve('pre-push'))")
fi
RESULT=$?

git stash pop -q
[ $RESULT -ne 0 ] && exit 1
exit 0

